FROM alpine:latest

LABEL maintainer="Lucas Belfanti"

# Install necessary dependencies
RUN apk update && apk add --no-cache curl  \
    && rm -rf /var/cache/apk/*

# Make HTTP request to /migrations/run/v1 endpoint
CMD ["sh", "-c", "curl -X POST http://app:8090/migrations/run/v1"]

