FROM alpine:3.21.0

# Maintainer
LABEL maintainer="Lucas Belfanti"

# Install necessary dependencies
RUN apk update && apk add --no-cache curl tzdata  \
    && rm -rf /var/cache/apk/*

# Set timezone
ENV TZ=America/Argentina/Buenos_Aires

# Make HTTP request to /migrations/run/v1 endpoint
CMD ["sh", "-c", " \
    echo ' ' && \
    echo 'Migrations execution: started' && \
    echo ' ' && \
    curl -X POST http://corpus_creator:${API_PORT}/migrations/run/v1 && \
    echo ' ' && \
    echo 'Migrations execution: finished' && \
    echo ' ' \
"]