FROM alpine:latest

LABEL maintainer="Lucas Belfanti"

# Install necessary dependencies
RUN apk update && apk add --no-cache curl tzdata  \
    && rm -rf /var/cache/apk/*

# Set timezone
ENV TZ=America/Argentina/Buenos_Aires

# Make HTTP requests to /migrations/run/v1 and /criteria/init/v1 endpoints
CMD ["sh", "-c", " \
    echo ' ' && \
    echo 'Migrations execution: started' && \
    curl -X POST http://ahbcc:${API_PORT}/migrations/run/v1 && \
    echo 'Migrations execution: finished' && \
    echo ' ' && \
    echo 'Criteria initialization: started' && \
    curl -X POST http://ahbcc:${API_PORT}/criteria/init/v1 && \
    echo 'Criteria initialization: finished' && \
    echo ' ' \
"]